env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - '*.js'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - warn
    - single
    - { "avoidEscape": true }
  semi:
    - warn
    - never
  object-curly-spacing:
    - warn
    - always
    - { "objectsInObjects": false, "arraysInObjects": false }
