@startmindmap

<style>
mindmapDiagram {
  .primitive {
    BackgroundColor #lightgreen
  }
  .type {
    BackgroundColor #lightblue
  }
  .abstractClass {
    BackgroundColor #Gold
  }
  .singleToneClass {
    BackgroundColor #GoldenRod
  }
  .class {
    BackgroundColor #Yellow
  }
  .null {
    BackgroundColor #green
  }
  .enum {
    BackgroundColor #violet
  }
  .enumItem {
    BackgroundColor #pink
  }
}
</style>

* PrimitiveType <<type>>
** null <<null>>
** boolean <<primitive>>
** number <<primitive>>
** string <<primitive>>

* SelectItem <<type>>
** ColumnLike <<type>>
*** Column <<class>>
*** Expression <<class>>
** Asterisk <<class>>

* OrderByArgsElement <<type>>
** OrderByNullsPosition <<abstractClass>>
*** NULLS_POSITION_NOT_EXIST <<singleToneClass>>
*** NULLS_FIRST <<singleToneClass>>
*** NULLS_LAST <<singleToneClass>>
** OrderByDirection <<abstractClass>>
*** DIRECTION_NOT_EXIST <<singleToneClass>>
*** ASC <<singleToneClass>>
*** DESC <<singleToneClass>>
** OrderByItemInfo <<class>>
** OrderByItem <<type>>
*** Column <<class>>
*** Expression <<class>>
*** string <<primitive>>

* OperandType <<type>>
** Expression <<class>>
** ValueType <<type>>
*** null <<null>>
*** BooleanLike <<type>>
**** boolean <<primitive>>
**** BooleanColumn <<class>>
*** NumberLike <<type>>
**** number <<primitive>>
**** NumberColumn <<class>>
*** TextLike <<type>>
**** string <<primitive>>
**** TextColumn  <<class>>

* Operator <<type>>
** ArithmeticOperator <<enum>>
*** ADD = '+' <<enumItem>>
*** SUB = '-' <<enumItem>>
*** MUL = '*' <<enumItem>>
*** DIV = '/' <<enumItem>>
*** MOD = '%' <<enumItem>>
*** EXP = '^' <<enumItem>>
** TextOperator <<enum>>
*** CONCAT = '||' <<enumItem>>
** Qualifier <<type>>
*** ComparisonOperator <<enum>>
**** Equal = '=' <<enumItem>>
**** NotEqual = '<>' <<enumItem>>
**** GreaterThan = '>' <<enumItem>>
**** GreaterOrEqual = '>=' <<enumItem>>
**** LesserThan = '<' <<enumItem>>
**** LesserOrEqual = '<=' <<enumItem>>
*** NullOperator <<enum>>
**** Is = 'IS' <<enumItem>>
**** IsNot = 'IS NOT' <<enumItem>>

@endmindmap
