name: Validate Version

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  validate_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate Version
        if: github.event.pull_request.base.ref == 'main'
        run: |
          version=$(jq -r '.version' package.json)
          if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]$ ]]; then
            echo "Invalid semver version found in package.json. Please fix the version and try again."
            exit 1
          else
            echo "Valid semver version found: $version"
            exit 0
          fi
