name: Publish sedk-mysql@next
on:
  release:
    types: [ prereleased ]
    tags:
      - sedk-mysql/v*.*.*-next.*

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          always-auth: true
          cache: yarn
      - run: yarn workspace sedk-mysql install --frozen-lockfile
      - run: yarn workspace sedk-mysql publish --access public --no-git-tag-version --new-version $(jq -r '.version' packages/sedk-mysql/package.json) --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MYSQL_PUBLISH_AUTH_TOKEN }}
