name: Publish sedk-postgres@latest
on:
  release:
    types: [ released ]
    tags: [ sedk-postgres/v*.*.* ]

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          always-auth: true
          cache: yarn
      - run: yarn workspace sedk-postgres install --frozen-lockfile
      - run: yarn workspace sedk-postgres publish --access public --no-git-tag-version --new-version $(jq -r '.version' packages/sedk-postgres/package.json) --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.POSTGRES_PUBLISH_AUTH_TOKEN }}
