name: Publish sedk-postgres@latest
on:
  release:
    types: [ released ]
    tags: [ "sedk-postgres/v*.*.*" ]

env:
  TAG_NAME: ${{ github.event.release.tag_name }}
  PACKAGE_VERSION: "" # to be filled later after checkout

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          always-auth: true
          cache: yarn

      - name: get package version
        run: |
          PACKAGE_VERSION=$(jq -r '.version' packages/sedk-postgres/package.json)
          echo "PACKAGE_VERSION=$PACKAGE_VERSION"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: validate tag name
        run: |
            if [[ ! $TAG_NAME =~ ^sedk-postgres\/v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$ ]]; then
                echo "❌ Invalid tag name: $TAG_NAME not suitable for latest release"
                exit 1
            else
                echo "✅ Valid tag name: $TAG_NAME"
            fi
      - name: validate version in package.json
        run: |
            if [[ ! $PACKAGE_VERSION =~ ^([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)$ ]]; then
                echo "❌ Invalid version name: $PACKAGE_VERSION not suitable for latest release"
                exit 1
            else
                echo "✅ Valid version: $PACKAGE_VERSION"
            fi
      - name: check if version in package.json is matching tag name
        run: |
            if [[ "sedk-postgres/v$PACKAGE_VERSION" != $TAG_NAME ]]; then
                echo "❌ Version in package.json: $PACKAGE_VERSION is not matching with tag name: $TAG_NAME"
                exit 1
            else
                echo "✅ Version in package.json is matching with tag name"
            fi

      - run: yarn workspace sedk-postgres install --frozen-lockfile
      - run: yarn workspace sedk-postgres publish --access public --no-git-tag-version --new-version $PACKAGE_VERSION --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.POSTGRES_PUBLISH_AUTH_TOKEN }}
