name: Publish sedk-mysql@next
on:
  release:
    types: [ prereleased ]
    tags:
      - sedk-mysql/v*-next.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
          cache: 'yarn'
      - run: yarn
        working-directory: ./packages/sedk-mysql
      - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MYSQL_PUBLISH_NPM_TOKEN }}
#      - run: yarn publish --access public --no-git-tag-version --new-version $(jq -r '.version' package.json) --tag next
      - run: yarn publish --userconfig .npmrc-publish --access public --no-git-tag-version --new-version $(jq -r '.version' package.json) --tag next
        working-directory: ./packages/sedk-mysql
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MYSQL_PUBLISH_NPM_TOKEN }}
