name: Validate Version

on:
  push:
    branches: [ "main", "stage" ]
  pull_request:
    branches: [main]

jobs:
  validate_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validate Version
        if: github.event.pull_request.base.ref == 'main'
        run: |
          package_json_files=$(find . -name 'package.json')
  
          for package_json in $package_json_files; do
            version=$(jq -r '.version' $package_json)
            if ! [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Invalid semver version: $version found in $package_json.\nPlease fix the version and try again."
              exit 1
            else
              echo "Valid semver version: $version found in $package_json."
            fi
          done
          exit 0
